name: "VSeek"
channels:
  - conda-forge
  - bioconda
  - anaconda
  - default
dependencies:
  - python>=3.10.0
  - bioconda::sra-tools==2.10.0
  - bioconda::entrezpy>=2.1.3
  - conda-forge::numpy>=1.22.0
  - conda-forge::matplotlib>=3.5.0
  - conda-forge::pandas>=1.4.0
  - conda-forge::seaborn>=0.11.0
  - conda-forge::lxml>=4.9.0
  - conda-forge::selenium>=4.2.0
  - conda-forge::webdriver-manager>=3.7.0
  - conda-forge::ipykernel>=6.13.0
  - conda-forge::dataframe_image>=0.1.0
  - conda-forge::plotly>=5.8.0
  - conda-forge::python-kaleido>=0.2.0
